"""Public package interface for AgentReplay."""

from agentreplay.adapters.openai_agents import (
    AgentReplay,
    OpenAIAgentsConfig,
    instrument,
    record_agent,
)
from agentreplay.api import configure, create_container, get_settings, reset_settings
from agentreplay.debugger import DebuggerEngine, DebuggerSession
from agentreplay.diff import DiffEngine
from agentreplay.exceptions import (
    AdapterError,
    AgentReplayError,
    ConfigurationError,
    DebuggerError,
    DiffError,
    InstrumentationError,
    ObservabilityError,
    PerformanceError,
    PluginError,
    ProfilerError,
    RedactionError,
    RegressionError,
    ReplayError,
    ReportingError,
    SDKError,
    SerializationError,
    StorageError,
)
from agentreplay.observability import (
    CorrelationContext,
    ObservabilityConfig,
    ObservabilityEngine,
    TelemetryExportResult,
    TelemetryMetrics,
    TelemetryTrace,
)
from agentreplay.performance import (
    BenchmarkCase,
    BenchmarkResult,
    BenchmarkSuite,
    SearchQuery,
    SearchResults,
    SQLiteOptimizer,
    StreamingTraceExporter,
    TraceSearchEngine,
    TraceWindowReader,
)
from agentreplay.plugins import AgentReplayPlugin, PluginApp, PluginManager
from agentreplay.profiler import ProfilerEngine, ProfilingReport
from agentreplay.recording import Recorder, record
from agentreplay.regression import (
    ImpactEstimate,
    MetricDelta,
    RegressionEngine,
    RegressionFinding,
    RegressionReport,
    RootCause,
    TrendAnalysis,
)
from agentreplay.replay import ReplayEngine
from agentreplay.reporting import ReportBundle, ReportingEngine, ReportOptions
from agentreplay.sdk import (
    SDK_API_VERSION,
    AgentReplaySDK,
    AnalyzerResult,
    ExportResult,
    ReportSection,
    SDKContext,
    SDKEventBus,
    SDKExtensionMetadata,
    SDKHookManager,
    create_sdk,
)
from agentreplay.security import (
    RedactionStrategy,
    SecurityConfig,
    SecurityEngine,
    SecurityFinding,
    SecurityReport,
    SecurityRule,
)
from agentreplay.storage import (
    EventQuery,
    Pagination,
    RunQuery,
    SQLiteStorage,
    StorageBackend,
)
from agentreplay.version import __version__

__all__ = [
    "__version__",
    "AdapterError",
    "AgentReplay",
    "AgentReplaySDK",
    "AgentReplayError",
    "ConfigurationError",
    "DebuggerEngine",
    "DebuggerError",
    "DebuggerSession",
    "DiffEngine",
    "DiffError",
    "EventQuery",
    "AnalyzerResult",
    "ExportResult",
    "ImpactEstimate",
    "InstrumentationError",
    "MetricDelta",
    "ObservabilityConfig",
    "ObservabilityEngine",
    "ObservabilityError",
    "OpenAIAgentsConfig",
    "Pagination",
    "PerformanceError",
    "PluginApp",
    "PluginError",
    "PluginManager",
    "ProfilerEngine",
    "ProfilerError",
    "ProfilingReport",
    "ReportBundle",
    "ReportSection",
    "ReportOptions",
    "ReportingEngine",
    "ReportingError",
    "RedactionError",
    "RedactionStrategy",
    "RegressionEngine",
    "RegressionError",
    "RegressionFinding",
    "RegressionReport",
    "ReplayError",
    "ReplayEngine",
    "Recorder",
    "RunQuery",
    "SecurityConfig",
    "SecurityEngine",
    "SecurityFinding",
    "SecurityReport",
    "SecurityRule",
    "SerializationError",
    "SDKError",
    "SDK_API_VERSION",
    "SDKContext",
    "SDKEventBus",
    "SDKExtensionMetadata",
    "SDKHookManager",
    "SQLiteStorage",
    "StorageError",
    "StorageBackend",
    "TelemetryExportResult",
    "TelemetryMetrics",
    "TelemetryTrace",
    "BenchmarkCase",
    "BenchmarkResult",
    "BenchmarkSuite",
    "AgentReplayPlugin",
    "CorrelationContext",
    "configure",
    "create_container",
    "create_sdk",
    "get_settings",
    "instrument",
    "record",
    "record_agent",
    "reset_settings",
    "RootCause",
    "SQLiteOptimizer",
    "SearchQuery",
    "SearchResults",
    "StreamingTraceExporter",
    "TraceSearchEngine",
    "TraceWindowReader",
    "TrendAnalysis",
]
